#!/bin/bash
#
# This script auto-detects system hardware (logical CPU cores)
# and generates a 'workload_config.sh' file with scaled
# stress-ng worker counts for data collection.
#
# (FIXED v3: Reduces the number of steps to ensure a
# practical runtime, trading completeness for speed.)
#

set -e

# --- Hardware Detection ---
N_CORES=$(nproc)
CONFIG_FILE="workload_config.sh"

echo "Detected $N_CORES logical cores."

# --- 1. Scaling Logic Definition (Practical) ---
#
# We use a fixed number of steps that represent percentages
# of the total cores. This keeps the total combinations
# fixed and manageable, regardless of core count.
#
# We use 'sort -un' to robustly handle low core counts
# where some values might be 0 or duplicates.
#
# 5 steps for main stressors: 0%, 25%, 50%, 100%, 200%
CPU_WORKERS=($(echo "0 $((N_CORES / 4)) $((N_CORES / 2)) $N_CORES $((N_CORES * 2))" | tr ' ' '\n' | sort -un))
SYS_WORKERS=($(echo "0 $((N_CORES / 4)) $((N_CORES / 2)) $N_CORES $((N_CORES * 2))" | tr ' ' '\n' | sort -un))

# 3 steps for secondary stressors: 0%, 50%, 100%
IO_WORKERS=($(echo "0 $((N_CORES / 2)) $N_CORES" | tr ' ' '\n' | sort -un))
CACHE_WORKERS=($(echo "0 $((N_CORES / 2)) $N_CORES" | tr ' ' '\n' | sort -un))

# 3 steps for other stressors: 0%, 100%, 200%
PIPE_WORKERS=($(echo "0 $N_CORES $((N_CORES * 2))" | tr ' ' '\n' | sort -un))

# 3 steps for VM (fixed): 0, 1, 2 workers
VM_WORKERS=(0 1 2)


# --- 2. Write the Configuration File ---
echo "Generating scaled workload configuration at '$CONFIG_FILE'..."

cat << EOF > $CONFIG_FILE
# --- Auto-generated Workload Configuration ---
# Generated for a system with $N_CORES logical cores.
# Do not edit this file directly. Re-run 'generate_config.sh' instead.

CPU_WORKERS=(${CPU_WORKERS[@]})
SYS_WORKERS=(${SYS_WORKERS[@]})
IO_WORKERS=(${IO_WORKERS[@]})
PIPE_WORKERS=(${PIPE_WORKERS[@]})
VM_WORKERS=(${VM_WORKERS[@]})
CACHE_WORKERS=(${CACHE_WORKERS[@]})

EOF

echo "Successfully generated '$CONFIG_FILE'."

# --- 3. Total Time Calculation ---
echo
echo "Calculating estimated total run time..."

LEN_CPU=${#CPU_WORKERS[@]}
LEN_SYS=${#SYS_WORKERS[@]}
LEN_IO=${#IO_WORKERS[@]}
LEN_PIPE=${#PIPE_WORKERS[@]}
LEN_VM=${#VM_WORKERS[@]}
LEN_CACHE=${#CACHE_WORKERS[@]}

TOTAL_RUNS=$(( LEN_CPU * LEN_SYS * LEN_IO * LEN_PIPE * LEN_VM * LEN_CACHE ))
VALID_RUNS=$(( TOTAL_RUNS - 1 )) # Subtract the 1 "all-zero" run

TIME_PER_RUN_SEC=$(( 45 + 2 + 15 )) # (stress + capture_cooldown + thermal_cooldown)
TOTAL_TIME_SEC=$(( VALID_RUNS * TIME_PER_RUN_SEC ))

HOURS=$(( TOTAL_TIME_SEC / 3600 ))
MINUTES=$(( (TOTAL_TIME_SEC % 3600) / 60 ))
SECONDS=$(( TOTAL_TIME_SEC % 60 ))

# --- 4. Print the Estimate ---
echo "---"
echo "Workload Run Estimate:"
echo "  - Time per combination: $TIME_PER_RUN_SEC seconds (45s stress + 2s capture + 15s cooldown)"
echo "  - Total combinations:   $LEN_CPU(cpu) x $LEN_SYS(sys) x $LEN_IO(io) x $LEN_PIPE(pipe) x $LEN_VM(vm) x $LEN_CACHE(cache) = $TOTAL_RUNS"
echo "  - Valid combinations:   $VALID_RUNS (subtracting the all-zero run)"
echo
echo "  ESTIMATED TOTAL TIME: $HOURS hours, $MINUTES minutes, $SECONDS seconds"
echo "---"
echo
echo "You can now run the main workload script:"
echo "sudo ./run_workloads.sh"
